// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0lTZHdGQZ0UxjQnPApvXZi5rz7ZAtUFU',
    appId: '1:873559048706:web:f2d6465074fafa80309d1b',
    messagingSenderId: '873559048706',
    projectId: 'rentacles-da066',
    authDomain: 'rentacles-da066.firebaseapp.com',
    storageBucket: 'rentacles-da066.appspot.com',
    measurementId: 'G-TBNSCYDWFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHk_7LKPgDahDPlL-Lih62AuWTgu0gyw',
    appId: '1:873559048706:android:b04e8c0ceb9f36ee309d1b',
    messagingSenderId: '873559048706',
    projectId: 'rentacles-da066',
    storageBucket: 'rentacles-da066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdBpNVHKt-E-dLqWl3yG2pqRfu3vlAmb4',
    appId: '1:873559048706:ios:0bcbb82c48c9c38b309d1b',
    messagingSenderId: '873559048706',
    projectId: 'rentacles-da066',
    storageBucket: 'rentacles-da066.appspot.com',
    androidClientId: '873559048706-8dfoc00tnjbcndegpbbupaknpu74mvr9.apps.googleusercontent.com',
    iosClientId: '873559048706-8n66805q8spqqk6ah8f5u6geu1nfha3u.apps.googleusercontent.com',
    iosBundleId: 'com.nmifzal.rentacles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdBpNVHKt-E-dLqWl3yG2pqRfu3vlAmb4',
    appId: '1:873559048706:ios:0bcbb82c48c9c38b309d1b',
    messagingSenderId: '873559048706',
    projectId: 'rentacles-da066',
    storageBucket: 'rentacles-da066.appspot.com',
    androidClientId: '873559048706-8dfoc00tnjbcndegpbbupaknpu74mvr9.apps.googleusercontent.com',
    iosClientId: '873559048706-8n66805q8spqqk6ah8f5u6geu1nfha3u.apps.googleusercontent.com',
    iosBundleId: 'com.nmifzal.rentacles',
  );
}
